name: Conditional PR Creator

on:
  workflow_dispatch:
  schedule:
    - cron: 0/15 * * * * # Every 15 minutes

jobs:
  check-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check if branch exists
        id: env
        run: |
          BRANCH_NAME="some-branch-name"
          echo "pr_branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          BRANCH_EXISTS=$(git ls-remote --heads origin $BRANCH_NAME)
          if [ -z "$BRANCH_EXISTS" ]; then
            echo "branch_exists=false" >> $GITHUB_OUTPUT
          else
            echo "branch_exists=true" >> $GITHUB_OUTPUT
          fi

      - name: Take action based on branch existence
        if: steps.env.outputs.branch_exists == 'false'
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: '${{steps.env.outputs.pr_branch_name}}'