name: create-release-branch 

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      platform:
        required: true
        type: string
      package:
        required: true
        type: string
      version:
        required: true
        type: string    
      arch:
        required: true
        type: string   
      release_link:
        required: false
        type: string    


jobs:
  reusable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check if branch exists
        id: env
        run: |
          BRANCH_EXISTS=$(git ls-remote --heads origin ${{inputs.branch}})
          if [ -z "$BRANCH_EXISTS" ]; then
            echo "branch_exists=false" >> $GITHUB_OUTPUT
          else
            echo "branch_exists=true" >> $GITHUB_OUTPUT
          fi
      # - name: Configure Git
      #   if: steps.env.outputs.branch_exists == 'false'
      #   run: |
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # - name: Create new branch
      #   if: steps.env.outputs.branch_exists == 'false'
      #   run: |
      #     git checkout -b ${{ inputs.branch }}
      #     git push origin ${{ inputs.branch }}
      - name: Make changes to pull request
        run: date +%s > report.txt
  
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7    
        with:
          committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          branch: ${{ inputs.branch }}
          title: '${{ inputs.branch }}'
          body: |
           New Release

           Package: ${{ inputs.package }}
           Version: ${{ inputs.version }}
           Platform: ${{ inputs.platform }}
           Architecture: ${{ inputs.arch }}

           This PR contains package updates generated via automated tooling.
           ${{ inputs.release_link || '' }}

          labels: |
            release
            amd64
          assignees: eenagy
          reviewers: eenagy
          draft: false
